framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
sensiolabs_typescript:
    source_dir: ['%kernel.project_dir%/assets']

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
