version: "3"
services:
  base:
    container_name: base
    build:
      context: ./docker/base/
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###
