name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']

    steps:
      - uses: actions/checkout@v4

      - name: Adding app folder as safe
        run: git config --global --add safe.directory /app

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions:  bz2, intl, pcntl, sodium, zip, xsl, gd, pdo_pgsql, pdo
          
      - name: Validate Composer dependencies
        uses: php-actions/composer@v6
        with:
          command: validate
          args: --strict
          working_dir: ./app
        
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./app

      - name: Run phpstan validation
        run: ./vendor/bin/phpstan analyse
        working-directory: ./app
