name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4

      - name: Adding app folder as safe
        run: git config --global --add safe.directory /app

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions:  bz2, intl, pcntl, sodium, zip, xsl, gd, pdo_pgsql, pdo
          
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./app

      - name: Run unit tests
        run: ./bin/phpunit --testdox --testsuite unit
        working-directory: ./app

      - name: Run integration tests
        run: ./bin/phpunit --testdox --testsuite integration
        working-directory: ./app

      - name: Run functional tests
        run: ./bin/phpunit --testdox --testsuite functional
        working-directory: ./app
